version: "3.9"
services:
  rails:
    platform: 'linux/amd64'
    build: .
    container_name: rails
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    platform: 'linux/amd64'
    image: mysql:8.0.27
    container_name: db
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  redis:
    container_name: redis
    # dockerホスト起動時にコンテナが起動するよう設定
    restart: always
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
volumes:
  db: